script: bash ./build_travis.sh
language: python
python:
  - 2.7
branches:
  only:
    - master
env:
  global:
    - secure: buWydUavu8o3wfa0Ctvo1lA2s/Vl3lr0fbhEPe7+OmiVNGhgdabmpgJXYIcDUh0hNVqQthpkRJ4T5QAsNpV/JPtbOB8X/HB0fuesItT+QgkVWVPaRdUfdYak0ihwwMHTNHcA5/MY8FYhdXMEx+VF/lLISMGuGFLgUeV7cVQMqFkGViH4b1EhwBhct4b/MN5HSI4FqNFDk2tT4qN8Tu2pJz8Wa2rgxkw3mld5Z9cKUtGD/Eky2T7Cyl1RJ+u7qhjiMQ4ZA0ys40JCI/c4LPeYDuqjtlVak+EghUy8x0Ds+vtjEIKp5LyC6mgDh07Dd4VQ9gcqa3/ECIdRJcWWbvRF8mg6Q8M+SYBGkdrHTJ0YhuIs5WQjsecJCf0ZGalWWz/lEBv/iBfo6iZ9DKwQWkLe/1s1g5hgj5t6oALNZb0Ob5KeE9kSJFFdGDuYtLr5uF5W1WP3otm+OxUQrUxi6CA+5DWmvA6FV/wJx9og8R+aK2oDiJzhlWvvvMMW6oZUMC2Gy4mZEBWGj487vyAGSXs80hKkTvHwojPJCIHkOuhO7w9T1Tp00jlPDt5+zhovp/77cNeSnCSn0SJ5eiutSS5FAJpH/hdwuXSOKDUtLWAEPXZ8Mwwj2X9Dpxm1A+ejM/30TSUFK5NkOvBCXBI4EgLj+pMpTSB7I7TeyxpOJbe3kJ0=
